Repository karilaa-dev/dev272-finalProject, pull requests merged in 2025-06, with the labels that each got.

#25 Create week 7 sprint closeout and rename previos one to the week 6
  retrospectives/week06-sprint-closeout.md
  retrospectives/week07-sprint-closeout.md
Labels: task

#26 Proper week numbers for the sprint closeouts
  retrospectives/week06-sprint-closeout.md
  retrospectives/week07-sprint-closeout.md
  retrospectives/week08-sprint-closeout.md
Labels: bug, documentation

#38 Week 8 Sprint Retrospective & Sprint Closeout
  retrospectives/week08-sprint-closeout.md
  retrospectives/week08-team-sprint-retrospective.png
Labels: task

#42 Implement mood logging, filtering by user_id, and graph improvements
  app/(main)/wellmind.tsx
  app/(tabs)/_layout.tsx
  app/(tabs)/goals/index.tsx
  app/(tabs)/goals/new-goals.tsx
  app/(tabs)/journal/index.tsx
  app/(tabs)/journal/new-entry.tsx
  app/(tabs)/mood-graph.tsx
  app/+not-found.tsx
  app/_layout.tsx
  app/index.tsx
  components/(auth)/LoginForm.tsx
  components/(auth)/RegisterForm.tsx
  components/MoodReminder.tsx
  package-lock.json
  package.json
  week9-henrykirykovich-retrospective.docx
Labels: task

#44 Reformat code with Prettier
  app.json
  app/(auth)/_layout.tsx
  app/(auth)/login.tsx
  app/(auth)/profile-form.tsx
  app/(auth)/register.tsx
  app/(main)/_layout.tsx
  app/(main)/wellmind.tsx
  app/(tabs)/_layout.tsx
  app/(tabs)/goals/index.tsx
  app/(tabs)/goals/new-goals.tsx
  app/(tabs)/journal/index.tsx
  app/(tabs)/journal/new-entry.tsx
  app/(tabs)/mood-graph.tsx
  app/+not-found.tsx
  app/_layout.tsx
  components/(auth)/LoginForm.tsx
  components/(auth)/RegisterForm.tsx
  components/Collapsible.tsx
  components/ExternalLink.tsx
  components/HapticTab.tsx
  components/HelloWave.tsx
  components/MoodReminder.tsx
  components/ParallaxScrollView.tsx
  components/ThemedView.tsx
  components/ui/IconSymbol.ios.tsx
  components/ui/IconSymbol.tsx
  components/ui/TabBarBackground.ios.tsx
  tsconfig.json
  week9-henrykirykovich-retrospective.docx
Labels: enhancement

#49 Week 9 Sprint Retrospective & Sprint Closeout
  retrospectives/week09-sprint-closeout.md
  retrospectives/week09-team-sprint-retrospective.png
Labels: task

#55 Week 10 & 11 Sprint Retrospective & Sprint Closeout task
  retrospectives/week07-sprint-closeout.md
  retrospectives/week10-sprint-closeout.md
  retrospectives/week10-team-sprint-retrospective.png
  retrospectives/week11-sprint-closeout.md
  retrospectives/week11-team-sprint-retrospective.png
Labels: task

#57 Docs fixes for final sumbission
  README.md
  retrospectives/week11-sprint-closeout.md
Labels: documentation
